version: "3"

services:
  web:
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8000:3000'

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=opextt
      - POSTGRES_DB=opextt
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  frontend:
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/usr/src/app
      - '/app/node_modules'
    build:
      context: ./frontend


